### PR TITLE
Permission System

### PR DESCRIPTION
**Pull request by Drxckzyz**
- Added a Permission System
- Added Perms to all Commands

### CODE REVIEW

**Comment by Drxckzyz** [comment]
Closing

**Review by RaymondJiang1 — COMMENTED** [review]
GoOd

**Comment by AMufInABox** [comment]
track anime

**Comment by RaymondJiang1** [comment]
Muffin... just why

**Comment by AMufInABox** [comment]
> Muffin... just why

ahahhaarialetetealtaeltatejetkteteteletn v

**Review by RaymondJiang1 — APPROVED** [review]
Yes

**Comment by Drxckzyz** [comment]
Why did u re open smh

**Comment by RaymondJiang1** [comment]
shush i forgot to merge

**Comment by Drxckzyz** [comment]
Smh

**Pull request merged**
